USE `erpdb`;

DROP PROCEDURE IF EXISTS  `SpSteelProductionFo`;

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SpSteelProductionFo`(
	V_DATE	CHAR(10),
	V_FO	DECIMAL(14,4),
	V_POWER	DECIMAL(14,4),
	V_USER	CHAR(5),
	V_PROC	CHAR(1)
	)
BEGIN
#	CALL SpSteelProductionFo('2019/03/31',15,1500,'B426','N');

DECLARE	V_PROJCD	CHAR(4);
DECLARE	V_FINYR		CHAR(4);
DECLARE	V_ST_DT		CHAR(10);
DECLARE	V_SUB_DT	CHAR(10);
DECLARE	V_CD_RO		CHAR(2);
DECLARE	V_CD_IO		CHAR(2);
DECLARE	V_CD_RA		CHAR(2);

DECLARE	V_VOCHCDR	CHAR(2);
DECLARE	V_VOCHCDI	CHAR(2);
DECLARE	V_VOCHNOR	INT;
DECLARE	V_VOCHNOI	INT;
DECLARE	C_VOCHNOR	INT;
DECLARE	C_VOCHNOI	INT;
DECLARE	S_VOCHNOR	CHAR(7);
DECLARE	S_VOCHNOI	CHAR(7);
DECLARE	STR_VOCHNOR	CHAR(24);
DECLARE	STR_VOCHNOI	CHAR(24);

DECLARE	V_FOILCD	CHAR(8);
DECLARE	V_POWERCD	CHAR(8);

DECLARE	V_PARTY		CHAR(5);

DECLARE	V_FO_OP		DECIMAL(14,4);

DECLARE	V_ERR_OCCURED	BOOLEAN;
DECLARE	V_ERR_MESSAGE	VARCHAR(500);

SET	V_PROJCD='201';
SET	V_ERR_OCCURED=FALSE;

SET	V_FOILCD='1001018';
SET	V_POWERCD='1001017';

SET	V_PARTY='S1301';

SET	V_CD_RO='RO';
SET	V_CD_IO='IO';
SET	V_CD_RA='RA';

SET	V_VOCHNOR=0;
SET	V_VOCHNOI=0;
SET	C_VOCHNOR=0;
SET	C_VOCHNOI=0;

SET	V_FINYR=
	CASE	
		WHEN SUBSTRING(V_DATE,6,2) IN ('01','02','03') THEN CONCAT(RIGHT(CAST((LEFT(V_DATE,4)-1) AS CHAR(4)),2),SUBSTRING(V_DATE,3,2))
		ELSE CONCAT(SUBSTRING(V_DATE,3,2),RIGHT(CAST((LEFT(V_DATE,4)+1) AS CHAR(4)),2))
	END;
SET	V_ST_DT=CONCAT('20',LEFT(V_FINYR,2),'/04/01');
IF V_ST_DT=V_DATE THEN
	SET	V_SUB_DT=V_DATE;
ELSE
	SET	V_SUB_DT=DATE_FORMAT(SUBDATE(CAST(V_DATE AS DATETIME),1),'%Y/%m/%d');
END IF;

SET	V_VOCHCDR=V_CD_RO;
SET	V_VOCHCDI=V_CD_IO;

DROP TEMPORARY TABLE IF EXISTS `TmpMReceipt`;
CREATE TEMPORARY TABLE `TmpMReceipt` (
  `LOCATION` CHAR(4) NOT NULL DEFAULT '0095',
  `PROJCD` CHAR(4) NOT NULL DEFAULT '201',
  `PARTY` CHAR(5) NOT NULL,
  `SRLNO` DECIMAL(6,0) NOT NULL,
  `VOCHCD` CHAR(2) NOT NULL,
  `VOCHNO` DECIMAL(6,0) NOT NULL,
  `VOCHDT` DATETIME DEFAULT NULL,
  `POPROJCD` CHAR(4) DEFAULT NULL,
  `POORDTYPE` CHAR(2) NOT NULL DEFAULT '',
  `PONO` CHAR(50) NOT NULL DEFAULT '',
  `POSRLNO` DECIMAL(6,0) NOT NULL DEFAULT '0',
  `ITEMCD` CHAR(8) NOT NULL,
  `NARR` CHAR(30) NOT NULL,
  `UNIT` CHAR(5) NOT NULL DEFAULT 'KW',
  `QTY` DECIMAL(10,4) NOT NULL DEFAULT '0.0000',
  `RATE` DECIMAL(12,2) NOT NULL DEFAULT '1',
  `CHALRT` DECIMAL(12,2) NOT NULL DEFAULT '1',
  `LANDVAL` DECIMAL(14,2) NOT NULL DEFAULT '1',
  `BSRNO` VARCHAR(6) NOT NULL DEFAULT '0',
  `BILLFLG` VARCHAR(6) NOT NULL DEFAULT '0',
  `BATCH` DECIMAL(6,0) NOT NULL DEFAULT '0',
  `REQ_NO` CHAR(14) NOT NULL DEFAULT '',
  `REF_DATE` DATETIME DEFAULT NULL,
  `BILL_NO` CHAR(20) NOT NULL DEFAULT '',
  `BILL_DATE` DATETIME NULL,
  `CHALLAN_NO` CHAR(20) NOT NULL DEFAULT '',
  `CHALLAN_DATE` DATETIME NULL,
  `TAXES` DECIMAL (12,2) NOT NULL DEFAULT '0',
  `TRANS_AMT` DECIMAL(12,2) NOT NULL DEFAULT '0',
  `OTH_AMT` DECIMAL(12,2) NOT NULL DEFAULT '0',
  `TOT_AMT` DECIMAL(12,2) NOT NULL DEFAULT '1',
  `USERID` VARCHAR(10) NOT NULL DEFAULT 'S710',
  `INSERTTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `GST_ID` CHAR(18) NOT NULL DEFAULT '',
  `GST_STCD` CHAR(3) NOT NULL DEFAULT '',
  `GST_AMOUNT` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `CGST_AMOUNT` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `SGST_AMOUNT` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `IGST_AMOUNT` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `VAT_VAL` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `ED_VAL` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `CHQNO` CHAR(8) NOT NULL DEFAULT '',
  `CHQDT` DATE NULL,
  `BILLNO` CHAR(24) NOT NULL DEFAULT '',
  `BILLDT` DATE NULL
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;
DROP TEMPORARY TABLE IF EXISTS `TmpTmtIssue`;
CREATE TEMPORARY TABLE `TmpTmtIssue` (
  `LOCATION` CHAR(4) NOT NULL DEFAULT '0095',
  `PROJCD` CHAR(4) NOT NULL DEFAULT '201',
  `PARTY` CHAR(5) NOT NULL,
  `SRLNO` INT(6) NOT NULL DEFAULT '1',
  `VOCHCD` CHAR(2) NOT NULL DEFAULT '',
  `VOCHNO` DECIMAL(6,0) NOT NULL DEFAULT '0',
  `VOCHDT` DATETIME NULL,
  `ITEMCD` CHAR(8) NOT NULL DEFAULT '',
  `NARR` CHAR(30) NOT NULL DEFAULT '',
  `UNIT` CHAR(8) NOT NULL DEFAULT 'MILL',
  `QTY` DECIMAL(10,4) NOT NULL DEFAULT '0',
  `VALUE1` DECIMAL(14,2) NOT NULL DEFAULT '0',
  `UNITCD` CHAR(8) NOT NULL DEFAULT '',
  `SUBLOC` CHAR(8) NOT NULL DEFAULT '10101',
  `MACHCD` CHAR(8) NOT NULL DEFAULT '',
  `MACHUNIT` CHAR(8) NOT NULL DEFAULT '',
  `USERID` VARCHAR(10) NOT NULL DEFAULT 'S710',
  `INSERTTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `RATE1` DECIMAL(14,2) NOT NULL DEFAULT '0.00',
  `GSTRATE2` DECIMAL(14,2) NOT NULL DEFAULT '0.00',
  `GSTVALUE2` DECIMAL(14,2) NOT NULL DEFAULT '0.00'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

SELECT		IFNULL(SUM(QTY),0)
FROM
(
SELECT		OPQTY AS QTY
FROM		MITOPBAL
WHERE		FINYR=V_FINYR
AND		PROJCD=V_PROJCD
AND		ITEMCD=V_FOILCD
UNION ALL
SELECT		QTY
FROM		MRECEIPT
WHERE		PROJCD=V_PROJCD
AND		ITEMCD=V_FOILCD
AND		VOCHCD=V_CD_RO
AND		VOCHDT BETWEEN V_ST_DT AND V_SUB_DT
UNION ALL
SELECT		((-1)*QTY) AS QTY
FROM		MISSUE
WHERE		PROJCD=V_PROJCD
AND		ITEMCD=V_FOILCD
AND		VOCHCD=V_CD_IO
AND		VOCHDT BETWEEN V_ST_DT AND V_SUB_DT
)		BILLET_STOCK	INTO	V_FO_OP;

SET	V_ERR_OCCURED=FALSE;
SET	V_ERR_MESSAGE=SPACE(0);
SET	STR_VOCHNOI=SPACE(0);
SET	STR_VOCHNOR=SPACE(0);
IF V_FO>V_FO_OP THEN
	SET	V_ERR_OCCURED=TRUE;
	SET	V_ERR_MESSAGE = 'Consumption Can Not Be Greater Than Opening';
END IF;
IF  V_FO<=0 THEN
	SET	V_ERR_OCCURED=TRUE;
	SET	V_ERR_MESSAGE = 'Furnace Oil Consumption Can Not Be Zero';
END IF;
IF  V_POWER<=0 THEN
	SET	V_ERR_OCCURED=TRUE;
	SET	V_ERR_MESSAGE = 'Power Consumption Can Not Be Zero';
END IF;

IF V_ERR_OCCURED = TRUE THEN

SELECT	STR_VOCHNOI AS FO,
	STR_VOCHNOR AS POWER,
	V_ERR_MESSAGE AS ERR_INFO;

ELSE

TRUNCATE TABLE	TmpTmtIssue;
TRUNCATE TABLE	TmpMReceipt;

SELECT	COUNT(*)
FROM	MISSUE
WHERE	PROJCD=V_PROJCD
AND	ITEMCD IN (V_FOILCD,V_POWERCD)
AND	VOCHCD=V_VOCHCDI
AND	VOCHDT=V_DATE	INTO C_VOCHNOI;
IF C_VOCHNOI>0 THEN
	SELECT		DISTINCT VOCHNO
	FROM		MISSUE
	WHERE		PROJCD=V_PROJCD
	AND		ITEMCD IN (V_FOILCD,V_POWERCD)
	AND		VOCHCD=V_VOCHCDI
	AND		VOCHDT=V_DATE
	ORDER BY	VOCHNO
	LIMIT		1	INTO V_VOCHNOI;
ELSE
	SELECT	(IFNULL(MAX(VOCHNO),0)+1)
	FROM	MISSUE
	WHERE	PROJCD=V_PROJCD	INTO	V_VOCHNOI;
END IF;

SELECT	COUNT(*)
FROM	MRECEIPT
WHERE	PROJCD=V_PROJCD
AND	ITEMCD=V_POWERCD
AND	VOCHCD=V_VOCHCDR
AND	VOCHDT=V_DATE	INTO C_VOCHNOR;
IF C_VOCHNOR>0 THEN
	SELECT		DISTINCT VOCHNO
	FROM		MRECEIPT
	WHERE		PROJCD=V_PROJCD
	AND		ITEMCD=V_POWERCD
	AND		VOCHCD=V_VOCHCDR
	AND		VOCHDT=V_DATE
	ORDER BY	VOCHNO
	LIMIT		1	INTO V_VOCHNOR;
ELSE
	SELECT	(IFNULL(MAX(VOCHNO),0)+1)
	FROM	MRECEIPT
	WHERE	PROJCD=V_PROJCD
	AND	VOCHCD<>V_CD_RA	INTO	V_VOCHNOR;
END IF;

SET	S_VOCHNOI=
		CASE
			WHEN V_VOCHNOI < 10 THEN CONCAT('000000',CAST(V_VOCHNOI AS CHAR(1)))
			WHEN V_VOCHNOI BETWEEN 10 AND 99 THEN CONCAT('00000',CAST(V_VOCHNOI AS CHAR(2)))
			WHEN V_VOCHNOI BETWEEN 100 AND 999 THEN CONCAT('0000',CAST(V_VOCHNOI AS CHAR(3)))
			WHEN V_VOCHNOI BETWEEN 1000 AND 9999 THEN CONCAT('000',CAST(V_VOCHNOI AS CHAR(4)))
			WHEN V_VOCHNOI BETWEEN 10000 AND 99999 THEN CONCAT('00',CAST(V_VOCHNOI AS CHAR(5)))
			WHEN V_VOCHNOI BETWEEN 100000 AND 999999 THEN CONCAT('0',CAST(V_VOCHNOI AS CHAR(6)))
			WHEN V_VOCHNOI > 999999 THEN CAST(V_VOCHNOI AS CHAR(7))
		END;
SET	S_VOCHNOR=
		CASE
			WHEN V_VOCHNOR < 10 THEN CONCAT('000000',CAST(V_VOCHNOR AS CHAR(1)))
			WHEN V_VOCHNOR BETWEEN 10 AND 99 THEN CONCAT('00000',CAST(V_VOCHNOR AS CHAR(2)))
			WHEN V_VOCHNOR BETWEEN 100 AND 999 THEN CONCAT('0000',CAST(V_VOCHNOR AS CHAR(3)))
			WHEN V_VOCHNOR BETWEEN 1000 AND 9999 THEN CONCAT('000',CAST(V_VOCHNOR AS CHAR(4)))
			WHEN V_VOCHNOR BETWEEN 10000 AND 99999 THEN CONCAT('00',CAST(V_VOCHNOR AS CHAR(5)))
			WHEN V_VOCHNOR BETWEEN 100000 AND 999999 THEN CONCAT('0',CAST(V_VOCHNOR AS CHAR(6)))
			WHEN V_VOCHNOR > 999999 THEN CAST(V_VOCHNOR AS CHAR(7))
		END;


SET	STR_VOCHNOI=CONCAT(V_FINYR,'/0095/201/',V_VOCHCDI,'/',S_VOCHNOI);
SET	STR_VOCHNOR=CONCAT(V_FINYR,'/0095/201/',V_VOCHCDR,'/',S_VOCHNOR);

INSERT INTO	TmpTmtIssue
		(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,ITEMCD,UNITCD,NARR,QTY,VALUE1,USERID)
VALUES		(V_PARTY,1,V_VOCHCDI,V_VOCHNOI,V_DATE,V_FOILCD,'KL','FURNACE OIL',V_FO,ROUND(V_FO,2),V_USER);
INSERT INTO	TmpTmtIssue
		(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,ITEMCD,UNITCD,NARR,QTY,VALUE1,USERID)
VALUES		(V_PARTY,2,V_VOCHCDI,V_VOCHNOI,V_DATE,V_POWERCD,'KW','POWER CONSUMPTION',V_POWER,ROUND(V_POWER,2),V_USER);

INSERT INTO	TmpMReceipt
		(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,POPROJCD,
		REF_DATE,BILL_DATE,ITEMCD,NARR,QTY,LANDVAL,TOT_AMT,USERID)
VALUES		(V_PARTY,1,V_VOCHCDR,V_VOCHNOR,V_DATE,V_PROJCD,
		V_DATE,V_DATE,V_POWERCD,'POWER CONSUMPTION',V_POWER,ROUND(V_POWER),ROUND(V_POWER),V_USER);

IF V_PROC='Y' THEN
	IF C_VOCHNOI>0 THEN
		DELETE
		FROM	MISSUE
		WHERE	PROJCD=V_PROJCD
		AND	ITEMCD IN (V_FOILCD,V_POWERCD)
		AND	VOCHCD=V_VOCHCDI
		AND	VOCHDT=V_DATE;
	END IF;
	IF C_VOCHNOR>0 THEN
		DELETE
		FROM	MRECEIPT
		WHERE	PROJCD=V_PROJCD
		AND	ITEMCD=V_POWERCD
		AND	VOCHCD=V_VOCHCDR
		AND	VOCHDT=V_DATE;
	END IF;

	SET	V_ERR_OCCURED=FALSE;
	BEGIN
		DECLARE EXIT HANDLER FOR SQLEXCEPTION
			SET	V_ERR_OCCURED=TRUE;

		SET AUTOCOMMIT = 0;
		START TRANSACTION;

		INSERT INTO MISSUE
		SELECT * FROM TmpTmtIssue;
		INSERT INTO MRECEIPT
		SELECT * FROM TmpMReceipt;

		COMMIT;
		SET AUTOCOMMIT = 1;

		SELECT	STR_VOCHNOI AS FO,
			STR_VOCHNOR AS POWER,
			V_ERR_MESSAGE AS ERR_INFO;
	END;
	IF V_ERR_OCCURED=TRUE THEN
		ROLLBACK;
		SET AUTOCOMMIT = 1;
		SET	V_ERR_MESSAGE = 'Processing Error';

		SELECT	STR_VOCHNOI AS FO,
			STR_VOCHNOR AS POWER,
			V_ERR_MESSAGE AS ERR_INFO;
	END IF;
ELSE
	SELECT * FROM TmpTmtIssue;
	SELECT * FROM TmpMReceipt;
END IF;

END IF;

DROP TEMPORARY TABLE IF EXISTS `TmpTmtIssue`;
DROP TEMPORARY TABLE IF EXISTS `TmpMReceipt`;

    END $$
DELIMITER ;