USE `erpdb`;

DROP PROCEDURE IF EXISTS  `SpSteelProductionTmt`;

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SpSteelProductionTmt`(
	V_DATE	CHAR(10),
	V_JOB	CHAR(2),
	V_BILET	DECIMAL(14,4),
	V_TMT08	DECIMAL(14,4),
	V_TMT10	DECIMAL(14,4),
	V_TMT12	DECIMAL(14,4),
	V_TMT16	DECIMAL(14,4),
	V_TMT20	DECIMAL(14,4),
	V_TMT25	DECIMAL(14,4),
	V_TMT28	DECIMAL(14,4),
	V_TMT32	DECIMAL(14,4),
	V_MR	DECIMAL(14,4),
	V_MS	DECIMAL(14,4),
	V_SC	DECIMAL(14,4),
	V_USER	CHAR(5),
	V_PROC	CHAR(1)
	)
BEGIN
#	CALL SpSteelProductionTmt('2019/03/31','02',245,15,45,10,60,20,30,20,35,3.5,3.5,3,'B426','N');

DECLARE	V_PROJCD	CHAR(4);
DECLARE	V_FINYR		CHAR(4);
DECLARE	V_ST_DT		CHAR(10);
DECLARE	V_SUB_DT	CHAR(10);
DECLARE	V_CD_RO		CHAR(2);
DECLARE	V_CD_IO		CHAR(2);
DECLARE	V_CD_RP		CHAR(2);
DECLARE	V_CD_IP		CHAR(2);
DECLARE	V_CD_RC		CHAR(2);
DECLARE	V_CD_IC		CHAR(2);
DECLARE	V_CD_RA		CHAR(2);

DECLARE	V_VOCHCDR	CHAR(2);
DECLARE	V_VOCHCDI	CHAR(2);
DECLARE	V_VOCHNOR	INT;
DECLARE	V_VOCHNOI	INT;
DECLARE	C_VOCHNOR	INT;
DECLARE	C_VOCHNOI	INT;
DECLARE	S_VOCHNOR	CHAR(7);
DECLARE	S_VOCHNOI	CHAR(7);
DECLARE	STR_VOCHNOR	CHAR(24);
DECLARE	STR_VOCHNOI	CHAR(24);

DECLARE	V_BIL_PROD	CHAR(8);
DECLARE	V_TMT_PROD_08	CHAR(8);
DECLARE	V_TMT_PROD_10	CHAR(8);
DECLARE	V_TMT_PROD_12	CHAR(8);
DECLARE	V_TMT_PROD_16	CHAR(8);
DECLARE	V_TMT_PROD_20	CHAR(8);
DECLARE	V_TMT_PROD_25	CHAR(8);
DECLARE	V_TMT_PROD_28	CHAR(8);
DECLARE	V_TMT_PROD_32	CHAR(8);
DECLARE	V_MR_PROD	CHAR(8);
DECLARE	V_MS_PROD	CHAR(8);
DECLARE	V_EC_PROD	CHAR(8);
DECLARE	V_SC_PROD	CHAR(8);

DECLARE	V_PARTY_C	CHAR(5);
DECLARE	V_PARTY_SP	CHAR(5);
DECLARE	V_PARTY		CHAR(5);
DECLARE	V_SRLNO		INT;

DECLARE	V_TMT_GRP	CHAR(4);
DECLARE	V_MR_GRP	CHAR(4);
DECLARE	V_MS_GRP	CHAR(4);
DECLARE	V_EC_GRP	CHAR(4);
DECLARE	V_SC_GRP	CHAR(4);

DECLARE	V_BIL_OP	DECIMAL(14,4);

DECLARE	V_ERR_OCCURED	BOOLEAN;
DECLARE	V_ERR_MESSAGE	VARCHAR(500);

SET	V_PROJCD='201';
SET	V_ERR_OCCURED=FALSE;
SET	V_BIL_PROD='1001011';
SET	V_TMT_PROD_08='1002002';
SET	V_TMT_PROD_10='1002003';
SET	V_TMT_PROD_12='1002004';
SET	V_TMT_PROD_16='1002005';
SET	V_TMT_PROD_20='1002006';
SET	V_TMT_PROD_25='1002007';
SET	V_TMT_PROD_28='1002008';
SET	V_TMT_PROD_32='1002009';
SET	V_MR_PROD='1003001';
SET	V_MS_PROD='1004001';
SET	V_EC_PROD='1005001';
SET	V_SC_PROD='1006001';

SET	V_PARTY_C='M414';
SET	V_PARTY_SP='S1301';

SET	V_TMT_GRP='1002';
SET	V_MR_GRP='1003';
SET	V_MS_GRP='1004';
SET	V_EC_GRP='1005';
SET	V_SC_GRP='1006';

SET	V_CD_RO='RO';
SET	V_CD_IO='IO';
SET	V_CD_RP='RP';
SET	V_CD_IP='IP';
SET	V_CD_RC='RC';
SET	V_CD_IC='IC';
SET	V_CD_RA='RA';

SET	V_VOCHNOR=0;
SET	V_VOCHNOI=0;
SET	C_VOCHNOR=0;
SET	C_VOCHNOI=0;

SET	V_FINYR=
	CASE	
		WHEN SUBSTRING(V_DATE,6,2) IN ('01','02','03') THEN CONCAT(RIGHT(CAST((LEFT(V_DATE,4)-1) AS CHAR(4)),2),SUBSTRING(V_DATE,3,2))
		ELSE CONCAT(SUBSTRING(V_DATE,3,2),RIGHT(CAST((LEFT(V_DATE,4)+1) AS CHAR(4)),2))
	END;
SET	V_ST_DT=CONCAT('20',LEFT(V_FINYR,2),'/04/01');
IF V_ST_DT=V_DATE THEN
	SET	V_SUB_DT=V_DATE;
ELSE
	SET	V_SUB_DT=DATE_FORMAT(SUBDATE(CAST(V_DATE AS DATETIME),1),'%Y/%m/%d');
END IF;

IF V_JOB='01' THEN
	SET	V_PARTY=V_PARTY_SP;
	SET	V_VOCHCDR=V_CD_RP;
	SET	V_VOCHCDI=V_CD_IP;
ELSE
	SET	V_PARTY=V_PARTY_C;
	SET	V_VOCHCDR=V_CD_RC;
	SET	V_VOCHCDI=V_CD_IC;
END IF;

DROP TEMPORARY TABLE IF EXISTS `TmpMReceipt`;
CREATE TEMPORARY TABLE `TmpMReceipt` (
  `LOCATION` CHAR(4) NOT NULL DEFAULT '0095',
  `PROJCD` CHAR(4) NOT NULL DEFAULT '201',
  `PARTY` CHAR(5) NOT NULL,
  `SRLNO` DECIMAL(6,0) NOT NULL,
  `VOCHCD` CHAR(2) NOT NULL,
  `VOCHNO` DECIMAL(6,0) NOT NULL,
  `VOCHDT` DATETIME DEFAULT NULL,
  `POPROJCD` CHAR(4) DEFAULT NULL,
  `POORDTYPE` CHAR(2) NOT NULL DEFAULT '',
  `PONO` CHAR(50) NOT NULL DEFAULT '',
  `POSRLNO` DECIMAL(6,0) NOT NULL DEFAULT '0',
  `ITEMCD` CHAR(8) NOT NULL,
  `NARR` CHAR(30) NOT NULL,
  `UNIT` CHAR(5) NOT NULL DEFAULT 'MT',
  `QTY` DECIMAL(10,4) NOT NULL DEFAULT '0.0000',
  `RATE` DECIMAL(12,2) NOT NULL DEFAULT '1',
  `CHALRT` DECIMAL(12,2) NOT NULL DEFAULT '1',
  `LANDVAL` DECIMAL(14,2) NOT NULL DEFAULT '1',
  `BSRNO` VARCHAR(6) NOT NULL DEFAULT '0',
  `BILLFLG` VARCHAR(6) NOT NULL DEFAULT '0',
  `BATCH` DECIMAL(6,0) NOT NULL DEFAULT '0',
  `REQ_NO` CHAR(14) NOT NULL DEFAULT '',
  `REF_DATE` DATETIME DEFAULT NULL,
  `BILL_NO` CHAR(20) NOT NULL DEFAULT '',
  `BILL_DATE` DATETIME NULL,
  `CHALLAN_NO` CHAR(20) NOT NULL DEFAULT '',
  `CHALLAN_DATE` DATETIME NULL,
  `TAXES` DECIMAL(12,2) NOT NULL DEFAULT '0',
  `TRANS_AMT` DECIMAL(12,2) NOT NULL DEFAULT '0',
  `OTH_AMT` DECIMAL(12,2) NOT NULL DEFAULT '0',
  `TOT_AMT` DECIMAL(12,2) NOT NULL DEFAULT '1',
  `USERID` VARCHAR(10) NOT NULL DEFAULT 'S710',
  `INSERTTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `GST_ID` CHAR(18) NOT NULL DEFAULT '',
  `GST_STCD` CHAR(3) NOT NULL DEFAULT '',
  `GST_AMOUNT` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `CGST_AMOUNT` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `SGST_AMOUNT` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `IGST_AMOUNT` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `VAT_VAL` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `ED_VAL` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `CHQNO` CHAR(8) NOT NULL DEFAULT '',
  `CHQDT` DATE NULL,
  `BILLNO` CHAR(24) NOT NULL DEFAULT '',
  `BILLDT` DATE NULL
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;
DROP TEMPORARY TABLE IF EXISTS `TmpTmtIssue`;
CREATE TEMPORARY TABLE `TmpTmtIssue` (
  `LOCATION` CHAR(4) NOT NULL DEFAULT '0095',
  `PROJCD` CHAR(4) NOT NULL DEFAULT '201',
  `PARTY` CHAR(5) NOT NULL,
  `SRLNO` INT(6) NOT NULL DEFAULT '1',
  `VOCHCD` CHAR(2) NOT NULL DEFAULT '',
  `VOCHNO` DECIMAL(6,0) NOT NULL DEFAULT '0',
  `VOCHDT` DATETIME NULL,
  `ITEMCD` CHAR(8) NOT NULL DEFAULT '',
  `NARR` CHAR(30) NOT NULL DEFAULT '',
  `UNIT` CHAR(8) NOT NULL DEFAULT 'MILL',
  `QTY` DECIMAL(10,4) NOT NULL DEFAULT '0',
  `VALUE1` DECIMAL(14,2) NOT NULL DEFAULT '0',
  `UNITCD` CHAR(8) NOT NULL DEFAULT 'MT',
  `SUBLOC` CHAR(8) NOT NULL DEFAULT '10101',
  `MACHCD` CHAR(8) NOT NULL DEFAULT '',
  `MACHUNIT` CHAR(8) NOT NULL DEFAULT '',
  `USERID` VARCHAR(10) NOT NULL DEFAULT 'S710',
  `INSERTTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `RATE1` DECIMAL(14,2) NOT NULL DEFAULT '0.00',
  `GSTRATE2` DECIMAL(14,2) NOT NULL DEFAULT '0.00',
  `GSTVALUE2` DECIMAL(14,2) NOT NULL DEFAULT '0.00'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

SELECT		IFNULL(SUM(QTY),0)
FROM
(
SELECT		OPQTY AS QTY
FROM		MITOPBAL
WHERE		FINYR=V_FINYR
AND		PROJCD=V_PROJCD
AND		ITEMCD=V_BIL_PROD
UNION ALL
SELECT		QTY
FROM		MRECEIPT
WHERE		PROJCD=V_PROJCD
AND		ITEMCD=V_BIL_PROD
AND		VOCHCD IN (V_CD_RO,V_CD_RC,V_CD_RA)
AND		VOCHDT BETWEEN V_ST_DT AND V_SUB_DT
UNION ALL
SELECT		((-1)*QTY) AS QTY
FROM		MISSUE
WHERE		PROJCD=V_PROJCD
AND		ITEMCD=V_BIL_PROD
AND		VOCHCD IN (V_CD_IO,V_CD_IC)
AND		VOCHDT BETWEEN V_ST_DT AND V_SUB_DT
)		BILLET_STOCK	INTO	V_BIL_OP;

SET	V_ERR_OCCURED=FALSE;
SET	V_ERR_MESSAGE=SPACE(0);
SET	STR_VOCHNOI=SPACE(0);
SET	STR_VOCHNOR=SPACE(0);
IF  V_BILET>V_BIL_OP THEN
	SET	V_ERR_OCCURED=TRUE;
	SET	V_ERR_MESSAGE = 'Billet Consumption Can Not Be Greater Than Opening';
END IF;
IF  V_BILET<=0 THEN
	SET	V_ERR_OCCURED=TRUE;
	SET	V_ERR_MESSAGE = 'Billet Consumption Can Not Be Zero';
END IF;
IF  V_TMT08<0 THEN
	SET	V_TMT08=0;
END IF;
IF  V_TMT10<0 THEN
	SET	V_TMT10=0;
END IF;
IF  V_TMT12<0 THEN
	SET	V_TMT12=0;
END IF;
IF  V_TMT16<0 THEN
	SET	V_TMT16=0;
END IF;
IF  V_TMT20<0 THEN
	SET	V_TMT20=0;
END IF;
IF  V_TMT25<0 THEN
	SET	V_TMT25=0;
END IF;
IF  V_TMT28<0 THEN
	SET	V_TMT28=0;
END IF;
IF  V_TMT32<0 THEN
	SET	V_TMT32=0;
END IF;
IF  V_MR<0 THEN
	SET	V_MR=0;
END IF;
IF  V_MS<0 THEN
	SET	V_MS=0;
END IF;
IF  V_SC<0 THEN
	SET	V_SC=0;
END IF;
IF (V_TMT08+V_TMT10+V_TMT12+V_TMT16+V_TMT20+V_TMT25+V_TMT28+V_TMT32)=0 THEN
	SET	V_ERR_OCCURED=TRUE;
	SET	V_ERR_MESSAGE = 'Nill Production Not Allowed';
END IF;
IF (V_MR+V_MS+V_SC)=0 THEN
	SET	V_ERR_OCCURED=TRUE;
	SET	V_ERR_MESSAGE = 'Nill Scrap Not Allowed';
END IF;
IF V_BILET<>(V_TMT08+V_TMT10+V_TMT12+V_TMT16+V_TMT20+V_TMT25+V_TMT28+V_TMT32+V_MR+V_MS+V_SC) THEN
	SET	V_ERR_OCCURED=TRUE;
	SET	V_ERR_MESSAGE = 'Billet Vs. Production Vs. Scrap Mis-Match';
END IF;

IF V_ERR_OCCURED = TRUE THEN

SELECT	STR_VOCHNOI AS BILLET,
	STR_VOCHNOR AS TMT,
	V_ERR_MESSAGE AS ERR_INFO;

ELSE

SET	V_SRLNO=0;

TRUNCATE TABLE	TmpTmtIssue;
TRUNCATE TABLE	TmpMReceipt;

SELECT	COUNT(*)
FROM	MISSUE
WHERE	PROJCD=V_PROJCD
AND	ITEMCD=V_BIL_PROD
AND	PARTY=V_PARTY
AND	VOCHCD=V_VOCHCDI
AND	VOCHDT=V_DATE	INTO C_VOCHNOI;
IF C_VOCHNOI>0 THEN
	SELECT		DISTINCT VOCHNO
	FROM		MISSUE
	WHERE		PROJCD=V_PROJCD
	AND		ITEMCD=V_BIL_PROD
	AND		PARTY=V_PARTY
	AND		VOCHCD=V_VOCHCDI
	AND		VOCHDT=V_DATE
	ORDER BY	VOCHNO
	LIMIT		1	INTO V_VOCHNOI;
ELSE
	SELECT	(IFNULL(MAX(VOCHNO),0)+1)
	FROM	MISSUE
	WHERE	PROJCD=V_PROJCD	INTO	V_VOCHNOI;
END IF;

SELECT	COUNT(*)
FROM	MRECEIPT
WHERE	PROJCD=V_PROJCD
AND	LENGTH(TRIM(ITEMCD))=7
AND	LEFT(TRIM(ITEMCD),4) IN (V_TMT_GRP,V_MR_GRP,V_MS_GRP,V_EC_GRP,V_SC_GRP)
AND	PARTY=V_PARTY
AND	VOCHCD=V_VOCHCDR
AND	VOCHDT=V_DATE	INTO C_VOCHNOR;
IF C_VOCHNOR>0 THEN
	SELECT		DISTINCT VOCHNO
	FROM		MRECEIPT
	WHERE		PROJCD=V_PROJCD
	AND		LENGTH(TRIM(ITEMCD))=7
	AND		LEFT(TRIM(ITEMCD),4) IN (V_TMT_GRP,V_MR_GRP,V_MS_GRP,V_EC_GRP,V_SC_GRP)
	AND		PARTY=V_PARTY
	AND		VOCHCD=V_VOCHCDR
	AND		VOCHDT=V_DATE
	ORDER BY	VOCHNO
	LIMIT		1	INTO V_VOCHNOR;
ELSE
	SELECT	(IFNULL(MAX(VOCHNO),0)+1)
	FROM	MRECEIPT
	WHERE	PROJCD=V_PROJCD
	AND	VOCHCD<>V_CD_RA	INTO	V_VOCHNOR;
END IF;

SET	S_VOCHNOI=
		CASE
			WHEN V_VOCHNOI < 10 THEN CONCAT('000000',CAST(V_VOCHNOI AS CHAR(1)))
			WHEN V_VOCHNOI BETWEEN 10 AND 99 THEN CONCAT('00000',CAST(V_VOCHNOI AS CHAR(2)))
			WHEN V_VOCHNOI BETWEEN 100 AND 999 THEN CONCAT('0000',CAST(V_VOCHNOI AS CHAR(3)))
			WHEN V_VOCHNOI BETWEEN 1000 AND 9999 THEN CONCAT('000',CAST(V_VOCHNOI AS CHAR(4)))
			WHEN V_VOCHNOI BETWEEN 10000 AND 99999 THEN CONCAT('00',CAST(V_VOCHNOI AS CHAR(5)))
			WHEN V_VOCHNOI BETWEEN 100000 AND 999999 THEN CONCAT('0',CAST(V_VOCHNOI AS CHAR(6)))
			WHEN V_VOCHNOI > 999999 THEN CAST(V_VOCHNOI AS CHAR(7))
		END;
SET	S_VOCHNOR=
		CASE
			WHEN V_VOCHNOR < 10 THEN CONCAT('000000',CAST(V_VOCHNOR AS CHAR(1)))
			WHEN V_VOCHNOR BETWEEN 10 AND 99 THEN CONCAT('00000',CAST(V_VOCHNOR AS CHAR(2)))
			WHEN V_VOCHNOR BETWEEN 100 AND 999 THEN CONCAT('0000',CAST(V_VOCHNOR AS CHAR(3)))
			WHEN V_VOCHNOR BETWEEN 1000 AND 9999 THEN CONCAT('000',CAST(V_VOCHNOR AS CHAR(4)))
			WHEN V_VOCHNOR BETWEEN 10000 AND 99999 THEN CONCAT('00',CAST(V_VOCHNOR AS CHAR(5)))
			WHEN V_VOCHNOR BETWEEN 100000 AND 999999 THEN CONCAT('0',CAST(V_VOCHNOR AS CHAR(6)))
			WHEN V_VOCHNOR > 999999 THEN CAST(V_VOCHNOR AS CHAR(7))
		END;


SET	STR_VOCHNOI=CONCAT(V_FINYR,'/0095/201/',V_VOCHCDI,'/',S_VOCHNOI);
SET	STR_VOCHNOR=CONCAT(V_FINYR,'/0095/201/',V_VOCHCDR,'/',S_VOCHNOR);

INSERT INTO	TmpTmtIssue
		(PARTY,VOCHCD,VOCHNO,VOCHDT,ITEMCD,NARR,QTY,VALUE1,USERID)
VALUES		(V_PARTY,V_VOCHCDI,V_VOCHNOI,V_DATE,V_BIL_PROD,'BILLET 100X100X3',V_BILET,ROUND(V_BILET,2),V_USER);

IF V_TMT08>0 THEN
	SET	V_SRLNO=(V_SRLNO+1);
	INSERT INTO	TmpMReceipt
			(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,POPROJCD,
			REF_DATE,BILL_DATE,ITEMCD,NARR,QTY,LANDVAL,TOT_AMT,USERID)
	VALUES		(V_PARTY,V_SRLNO,V_VOCHCDR,V_VOCHNOR,V_DATE,V_PROJCD,
			V_DATE,V_DATE,V_TMT_PROD_08,'TMT 08 MM',V_TMT08,ROUND(V_TMT08),ROUND(V_TMT08),V_USER);
END IF;
IF V_TMT10>0 THEN
	SET	V_SRLNO=(V_SRLNO+1);
	INSERT INTO	TmpMReceipt
			(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,POPROJCD,
			REF_DATE,BILL_DATE,ITEMCD,NARR,QTY,LANDVAL,TOT_AMT,USERID)
	VALUES		(V_PARTY,V_SRLNO,V_VOCHCDR,V_VOCHNOR,V_DATE,V_PROJCD,
			V_DATE,V_DATE,V_TMT_PROD_10,'TMT 10 MM',V_TMT10,ROUND(V_TMT10),ROUND(V_TMT10),V_USER);
END IF;
IF V_TMT12>0 THEN
	SET	V_SRLNO=(V_SRLNO+1);
	INSERT INTO	TmpMReceipt
			(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,POPROJCD,
			REF_DATE,BILL_DATE,ITEMCD,NARR,QTY,LANDVAL,TOT_AMT,USERID)
	VALUES		(V_PARTY,V_SRLNO,V_VOCHCDR,V_VOCHNOR,V_DATE,V_PROJCD,
			V_DATE,V_DATE,V_TMT_PROD_12,'TMT 12 MM',V_TMT12,ROUND(V_TMT12),ROUND(V_TMT12),V_USER);
END IF;
IF V_TMT16>0 THEN
	SET	V_SRLNO=(V_SRLNO+1);
	INSERT INTO	TmpMReceipt
			(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,POPROJCD,
			REF_DATE,BILL_DATE,ITEMCD,NARR,QTY,LANDVAL,TOT_AMT,USERID)
	VALUES		(V_PARTY,V_SRLNO,V_VOCHCDR,V_VOCHNOR,V_DATE,V_PROJCD,
			V_DATE,V_DATE,V_TMT_PROD_16,'TMT 16 MM',V_TMT16,ROUND(V_TMT16),ROUND(V_TMT16),V_USER);
END IF;
IF V_TMT20>0 THEN
	SET	V_SRLNO=(V_SRLNO+1);
	INSERT INTO	TmpMReceipt
			(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,POPROJCD,
			REF_DATE,BILL_DATE,ITEMCD,NARR,QTY,LANDVAL,TOT_AMT,USERID)
	VALUES		(V_PARTY,V_SRLNO,V_VOCHCDR,V_VOCHNOR,V_DATE,V_PROJCD,
			V_DATE,V_DATE,V_TMT_PROD_20,'TMT 20 MM',V_TMT20,ROUND(V_TMT20),ROUND(V_TMT20),V_USER);
END IF;
IF V_TMT25>0 THEN
	SET	V_SRLNO=(V_SRLNO+1);
	INSERT INTO	TmpMReceipt
			(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,POPROJCD,
			REF_DATE,BILL_DATE,ITEMCD,NARR,QTY,LANDVAL,TOT_AMT,USERID)
	VALUES		(V_PARTY,V_SRLNO,V_VOCHCDR,V_VOCHNOR,V_DATE,V_PROJCD,
			V_DATE,V_DATE,V_TMT_PROD_25,'TMT 25 MM',V_TMT25,ROUND(V_TMT25),ROUND(V_TMT25),V_USER);
END IF;
IF V_TMT28>0 THEN
	SET	V_SRLNO=(V_SRLNO+1);
	INSERT INTO	TmpMReceipt
			(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,POPROJCD,
			REF_DATE,BILL_DATE,ITEMCD,NARR,QTY,LANDVAL,TOT_AMT,USERID)
	VALUES		(V_PARTY,V_SRLNO,V_VOCHCDR,V_VOCHNOR,V_DATE,V_PROJCD,
			V_DATE,V_DATE,V_TMT_PROD_28,'TMT 28 MM',V_TMT28,ROUND(V_TMT28),ROUND(V_TMT28),V_USER);
END IF;
IF V_TMT32>0 THEN
	SET	V_SRLNO=(V_SRLNO+1);
	INSERT INTO	TmpMReceipt
			(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,POPROJCD,
			REF_DATE,BILL_DATE,ITEMCD,NARR,QTY,LANDVAL,TOT_AMT,USERID)
	VALUES		(V_PARTY,V_SRLNO,V_VOCHCDR,V_VOCHNOR,V_DATE,V_PROJCD,
			V_DATE,V_DATE,V_TMT_PROD_32,'TMT 32 MM',V_TMT32,ROUND(V_TMT32),ROUND(V_TMT32),V_USER);
END IF;
IF V_MR>0 THEN
	SET	V_SRLNO=(V_SRLNO+1);
	INSERT INTO	TmpMReceipt
			(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,POPROJCD,
			REF_DATE,BILL_DATE,ITEMCD,NARR,QTY,LANDVAL,TOT_AMT,USERID)
	VALUES		(V_PARTY,V_SRLNO,V_VOCHCDR,V_VOCHNOR,V_DATE,V_PROJCD,
			V_DATE,V_DATE,V_MR_PROD,'MISS-ROLL',V_MR,ROUND(V_MR),ROUND(V_MR),V_USER);
END IF;
IF V_MS>0 THEN
	SET	V_SRLNO=(V_SRLNO+1);
	INSERT INTO	TmpMReceipt
			(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,POPROJCD,
			REF_DATE,BILL_DATE,ITEMCD,NARR,QTY,LANDVAL,TOT_AMT,USERID)
	VALUES		(V_PARTY,V_SRLNO,V_VOCHCDR,V_VOCHNOR,V_DATE,V_PROJCD,
			V_DATE,V_DATE,V_MS_PROD,'MILL-SCALE',V_MS,ROUND(V_MS),ROUND(V_MS),V_USER);
END IF;
IF V_SC>0 THEN
	SET	V_SRLNO=(V_SRLNO+1);
	INSERT INTO	TmpMReceipt
			(PARTY,SRLNO,VOCHCD,VOCHNO,VOCHDT,POPROJCD,
			REF_DATE,BILL_DATE,ITEMCD,NARR,QTY,LANDVAL,TOT_AMT,USERID)
	VALUES		(V_PARTY,V_SRLNO,V_VOCHCDR,V_VOCHNOR,V_DATE,V_PROJCD,
			V_DATE,V_DATE,V_SC_PROD,'SCRAP',V_SC,ROUND(V_SC),ROUND(V_SC),V_USER);
END IF;

SET	V_ERR_MESSAGE=SPACE(0);
IF V_PROC='Y' THEN
	SET	V_ERR_OCCURED=FALSE;
	BEGIN
		DECLARE EXIT HANDLER FOR SQLEXCEPTION
			SET	V_ERR_OCCURED=TRUE;

		SET AUTOCOMMIT = 0;
		START TRANSACTION;

		IF C_VOCHNOI>0 THEN
			DELETE
			FROM	MISSUE
			WHERE	PROJCD=V_PROJCD
			AND	ITEMCD=V_BIL_PROD
			AND	PARTY=V_PARTY
			AND	VOCHCD=V_VOCHCDI
			AND	VOCHDT=V_DATE;
		END IF;
		IF C_VOCHNOR>0 THEN
			DELETE
			FROM	MRECEIPT
			WHERE	PROJCD=V_PROJCD
			AND	LENGTH(TRIM(ITEMCD))=7
			AND	LEFT(TRIM(ITEMCD),4) IN (V_TMT_GRP,V_MR_GRP,V_MS_GRP,V_EC_GRP,V_SC_GRP)
			AND	PARTY=V_PARTY
			AND	VOCHCD=V_VOCHCDR
			AND	VOCHDT=V_DATE;
		END IF;

		INSERT INTO MISSUE
		SELECT * FROM TmpTmtIssue;
		INSERT INTO MRECEIPT
		SELECT * FROM TmpMReceipt;

		COMMIT;
		SET AUTOCOMMIT = 1;
	END;
	IF V_ERR_OCCURED=TRUE THEN
		ROLLBACK;
		SET AUTOCOMMIT = 1;
		SET	STR_VOCHNOI=SPACE(0);
		SET	STR_VOCHNOR=SPACE(0);
		SET	V_ERR_MESSAGE = 'Processing Error';
	END IF;

	SELECT	STR_VOCHNOI AS BILLET,
		STR_VOCHNOR AS TMT,
		V_ERR_MESSAGE AS ERR_INFO;
ELSE
	SELECT * FROM TmpTmtIssue;
	SELECT * FROM TmpMReceipt;
END IF;

END IF;

DROP TEMPORARY TABLE IF EXISTS `TmpTmtIssue`;
DROP TEMPORARY TABLE IF EXISTS `TmpMReceipt`;

    END $$
DELIMITER ;